### ISSUE TITLE
Create/Edit with VisualEditor is impossible with extension AuthRemoteuser activate

### ISSUE THREAD

**Issue by raadniball** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#10]
Create/Edit with VisualEditor is impossible with extension AuthRemoteuser activate

Visual Editor indicate Error 500

log apache (with extension AuthRemoteuser activate) 

localhost:80 127.0.0.1 - - [01/Feb/2017:15:17:47 +0100] "GET /wiki/api.php?format=json&action=query&prop=info%7Crevisions&rawcontinue=1&rvprop=content%7Cids%7Ctimestamp%7Cuser%7Cuserid%7Csize%7Csha1%7Ccontentmodel%7Ccomment&revids=155 HTTP/1.1" 500 523 "-" "Parsoid/0.6.1"

log apache ( with extension AuthRemoteuser inactivate)
localhost:80 127.0.0.1 - - [01/Feb/2017:15:20:46 +0100] "GET /wiki/api.php?format=json&action=query&prop=info%7Crevisions&rawcontinue=1&rvprop=content%7Cids%7Ctimestamp%7Cuser%7Cuserid%7Csize%7Csha1%7Ccontentmodel%7Ccomment&revids=155 HTTP/1.1" 200 4235 "-" "Parsoid/0.6.1"

**Comment by fnk** [comment]
Can you be more specific?
Please add some log data. What you posted just tells me that it did not work for you...

We also use VisualEditor together with AuthRemoteuser and the way we made it work is having another virtual host serving the wiki just for local requests, not doing authentication there but providing a system user for parsoid that can read the markup. The main reason for this is that our setup is HTTPS only and parsoid cannot deal with this.

The parsoid/api local vhost listens on HTTP
```
<Location "/wiki">
  Allow From All
  Satisfy Any
  SetEnv REMOTE_USER wiki_system_user
</Location>
```
This is the interesting part of the parsoid-config.yaml
```
services:
  - module: ../src/lib/index.js
    entrypoint: apiServiceWorker
    conf:
        mwApis:
        - # The URL of you MediaWiki API endpoint.
          uri: 'http://localhost/wiki/api.php'
          domain: 'localhost'
```

And this the relevant parts of `LocalSettings.php`
```
$wgEnableAPI = true;
wfLoadExtension('VisualEditor');
// Enable by default for everybody
$wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgVirtualRestConfig['modules']['parsoid'] = array(
    // Use port 8142 if you use the Debian package
    'url' => 'http://localhost:8142',
    'domain' => 'localhost',
    'forwardCookies' => true
);


```
